### ISSUE TITLE
Logging issues in custom log attributes and Pino log settings

### ISSUE THREAD

**Issue by gurjotkaur20** [godspeedsystems/gs-node-service#1017]
## Version Information

Server Version: 
@godspeedsystems/core: 2.5.1

## Current Behavior
**Pino log setting is not working:**
- [x] hostname is not displayed in Pino logs when it is true in `log.bindings` in `config/default.yaml`
```yaml title=config/default.yaml
lang: js
log:
  level: debug #by default info
  timestamp: stdTimeFunctions.isoTime #Pino date formats
  bindings: # should pid and hostname be enabled in pino log bindings.
    pid: false
    hostname: true 
```
![image](https://github.com/godspeedsystems/gs-node-service/assets/88080236/d371fe0a-a1cf-4c27-84a3-25322fd32864)

**Custom log attribute feature is not working in the below cases:**
- [x] At event level: [Check documentation here](https://godspeed.systems/docs/microservices-framework/telemetry/logging#2-at-event-level) Backward compatibility is not working. For example,
```yaml
"http.get./helloworld":
  fn: helloworld
  authn: false
  # v2 format is working
  log:
    attributes:
      event_type: helloworld
  # v1 compatible format is not working
  # log_attributes:
  #   event_type: helloworld
```
- [x] Custom on_error logging in workflow/tasks: [Check documentation here](https://godspeed.systems/docs/microservices-framework/telemetry/logging#3-custom-on_error-logging-in-workflowtasks) v2 compatible format is not working while backward compatibility is working. For example,
```yaml
id: helloworld
tasks:
  - id: first_task
    fn: com.gs.return
    args:
      success: false
    on_error:
      # backward compatible is working
      log_attributes:
        error_type: "enter your custom error type here"
        error_message: "xyz value is required"
      # v2 compatible is not working
      # log:
      #   attributes:
      #     error_type: "enter your custom error type here"
      #     error_message: "xyz value is required"
```
- [x] At eventsource level: should be working. For example,
```yaml
type: express
port: 3005
base_url: /api/v1 #the base url of the http service

#Basic swagger setup
docs:
  endpoint: /api-docs # the url on which the service will start

request_body_limit: 20000 # maximum size of the request body (in bytes)
file_size_limit: 50000 # How big a file can be uploaded (in bytes)

# not working
log:
  attributes:
    event_type: helloworld    
```

## Expected Behavior
The above scenarios should work properly.
