### ISSUE TITLE
Custom log attributes

### ISSUE THREAD

**Issue by xCodeMuse** [godspeedsystems/gs-node-service#600]
@event level

```
log_attributes:
  msgparameter:
     key1: value
  identifier: "params.id"
```

Developers can add custom log attributes which overrides default config values if any.
