### ISSUE TITLE
V2: Authz

### ISSUE THREAD

**Issue by kushal-godspeed** [godspeedsystems/gs-node-service#736]
### What we need
Authorization in the microservice framework should work at two levels: One of the event itself (p0), and second should be at the task and datasource level (p1). It should support multi level tenancy using ABAC apart from plain RBAC. The GSCloudEvent.user object can be filled by the eventsource plugin or as a task in the authz workflow. Then the remaining authz workflow tasks can access that information and enrich and use it further for authz logic.
#### What the core framework will not do
Framework will not handle authentication like JWT, parsing of headers and validating based on policies like JWT, and adding that information to the GSCloudEvent.user object. 
**Parsing JWT or other such keys can be done by either**

1. **The event source plugin**. FYI in case of JWT, we recommend standard jwt handling config to all event source plugin handlers. 

```yaml
jwt:
  issuer:
  audience:
  secretOrKey:
```
For all keys or protocols used, the eventsource needs to handle the header parsing and initializing the user object. 
2. **Writing a task in the authz workflow** which enriches the user object from the JWT or another key. 

### How the solution is to be designed
The authz workflow will take the core framework's workflows' tasks' DSL , or, the path of a function/workflow. 
```yaml
# example 1
authz: com.biz.custom_authz_workflow
# example 2
authz: 
  - id: enrich_context
    summary: |
        Enrich user information based on his parsed JWT, 
        from a policy engine, DB, some datasource
    fn: com.biz.enrich_user_context 
    args: 
      success: true
  # if above task returns GSStatus.success==true
  - summary: apply the rules over enriched context. Returns true or false
    fn: | 
      <% 
        success: user.role === 'admin' && user.department === 'HR'
      %>
  # if above task returns true or GSStatus.success==true
  - id: fetch_rules
    summary: |
      in case we need dynamically fetched and evaluated rules 
      from a rule engine like Drools or JRE rule engine storing rules
    fn: com.biz.load_dynamic_rules
  # if above task returns GSStatus.success==true
  - fn: com.gs.evaluate_gre


```

- Think of authz instruction as a workflow. It will accept an array of task or a single task, each of which should return GSStatus 
- These instructions may enrich the context and user data, or load and run authorization checks, or do both. 
- Following Zero trust policy, whenever GSStatus is not returned with success: true or when GSStatus.code === 403, the authorization will be considered failed. Next tasks in the series of tasks will not be executed. The event or workflow task at which the user's authz has failed will exit with GSStatus
```javascript
{
  success: false,
  code: 403,
  message: "Unauthorized Access",
  data: {
    custom_message_as_returned_by_authz_task: "Access failed because...",
    any_other_data_or_message: "something"
  }
}
```  
- For task level datasource access, any additional instructions like allowed or not allowed tables, rows, columns will be part of the data key of GSStatus returned by the authz workflow. The function invoked in the authorized task will know how to handle this information returned in a generic format. The GSStatus returned, along with the data object should look like this.
```javascript
{
  success: true,
  data: {
      "tableABC": {
        "where": {ownerId: <%user.user_id%>, departmentId: <%user.department_id%>}, // This is the additional where clause for authz, which must be added as part of the sql query to DB by the plugin. This clause will be in Prisma format.
        "can_access": ["column1","column2"] //The plugin should not allow to return or update any column outside this array. 
        "no_access": ["column1"] //The columns not allowed to be retrieved or updated. In case can_access is provided, then no_access will be not used. 
      }
  }
}
``` 

- Allow calling any yaml or js workflow which should return authz result in standard acceptable GSStatus format as discussed above.
- If authz is defined in eventsource level, it will be applied to all the events unless overridden or explicitly set to a false in an event def.

### How to implement the feature (steps)
> Note: As described above JWT or any header parsing and validation and initial user info initialization can be done by event source plugin or a task in authz workflow. This will not be part of the core framework
#### At the event level
- Eventsource loader to load and parse GSWorkflow from `authz` tag in eventsource definition (if found). This will be the default workflow for all events of that eventsource.
- Event loader to load and parse GSWorkflow from `authz` tag in event definition (if found). 
- Event authz def will override/replace the default authz def of eventsource for all events. `auth: falsy_value` will basically remove any authz logic for the given event.
- In processEvent() the core framework will first run the authz workflow. If it fails, the framework will return the GSStatus from the workflow. In case there is any runtime error not handled by the developer, the framework must return GSSatus: {500, 'Internal server error'} by default.

#### At the task level
- Framework function loader will load the authz workflow
- This workflow will be executed after the pre_task_hooks (if any) and before the actual task is run.
- Upon successful authz, the datasource's execute() method will get the `authz` GSStatus result in the `args` object. The plugin can access the data from `args.authz.data`. The shape of data will be as described in the steps above -  `tableName{where,can_access|no_access}`. 
- The plugin now needs to modify its query to the datasource and as per the authz data.

### Linked to
This issue #908 has some bugs related to this issue and are solved now and released in 3.0.0
