### ISSUE TITLE
The structure of response must be generic on success true/false [pinelabs]

### ISSUE THREAD

**Issue by kushal-godspeed** [godspeedsystems/gs-node-service#741]
Documentation needs an updation. how the gs_response/gs_status will be when a task is executed.
```
args:  
  success: true
  response: 
    test: true
    score: 1
```

in the above case the subsequent task is not able to get the response key, and returning only
```
success: true

expected response should be/ the subsequent task should be having the generic response access from the task executed before it.
  success: true
  response: 
    test: true
    score: 1
```
