### ISSUE TITLE
OAuth 2.0 authentication 

### ISSUE THREAD

**Issue by rohitgodspeed** [godspeedsystems/gs-node-service#768]

**Comment by mastersilv3r** [comment]
please add description and move it

**Comment by sundar-godspeed** [comment]
## Follow these steps to set up OAuth2 for login:

1. Configure OAuth2 in http.yaml
- Update your http.yaml file with the following OAuth2 configuration. Replace the placeholders with your actual values.

```yaml
oauth2:
  google_client_id:  <%config.google_client_id%> 
  google_client_secret: <%config.google_client_secret%>
  call_back_url: <%config.call_back_url%>
  success_redirect: <%config.success_redirect%>
  failure_redirect: <%config.failure_redirect%>
  session_secret: <%config.session_secret%>
Configure Google Credentials
```
2. Visit [Google Cloud Console](https://console.cloud.google.com/apis/credentials) to obtain your google_client_id, google_client_secret, and call_back_url.

3. Choose Between JWT and OAuth2
You can use either JWT or OAuth2, but not both simultaneously, else it throws an error. Ensure that your configuration aligns with your chosen authentication method.

4.  Authentication Endpoint
To authenticate, access the /auth/google endpoint. Example: http://localhost:3000/auth/google. Upon successful authentication, it redirects to the success_redirect; otherwise, it redirects to the failure_redirect.
