### ISSUE TITLE
Correct com.gs.return behavior in parallel case. This is a bug in both v1

### ISSUE THREAD

**Issue by rohitgodspeed** [godspeedsystems/gs-node-service#799]
**Requirement**: com.gs.parallel should return the output of all the parallel cases instead of a single task when the com.gs.return method is used in the parallel tasks.

**Current Implementation**: Per the existing implementation, if com.gs.return function is specified in any of the parallel task then the complete com.gs.parallel exits with com.gs.return output of the last task.

**Workflow**

```
id: return4
tasks:
  - id: parallel
    fn: com.gs.parallel
    tasks:
      - id: 1st
        fn: com.gs.return
        args: |
          'parallel task1'
      - id: 2nd
        fn: com.gs.return
        args: |
          'parallel task2'
  - id: output_task
    fn: com.gs.return
    args:
      name: 'parallel demo is finished'
```
**current output of above workflow**
```
'parallel task2'
```

**Expected Implementation:** com.gs.parallel task should return the output of all the parallel cases. For example, consider the following workflows and expected output:
 
Expected Output 
```
{ 'name': 'parallel demo is finished' }
```

workflow
```
id: return4
tasks:
  - id: parallel
    fn: com.gs.parallel
    tasks:
      - id: 1st
        fn: com.gs.return
        args: |
          'parallel task1'
      - id: 2nd
        fn: com.gs.return
        args: |
          'parallel task2'
  - id: output_task
    fn: com.gs.return
    args: <% outputs.parallel.data %>
```
expected output
```
[
  {
    "code": 200,
    "success": true,
    "data": "parallel task1"
  },
  {
    "code": 200,
    "success": true,
    "data": "parallel task2"
  }
]
```

**Documentation**: Update com.gs.return and com.gs.parallel documentation for having two different behaviors of com.gs.return method: Exit from the current workflow except com.gs.parallel (where it will only return from the task, not the workflow.)

Workflow 
```
id: return4
tasks:
  - id: parallel
    fn: com.gs.parallel
    tasks:
      - id: parallel
        fn: com.gs.parallel
        tasks:
          - id: 1st
            fn: com.gs.return
            args: "నమస్కారం"

          - id: 2nd
            fn: com.gs.return
            args: "नमस्ते"

          - id: 3rd
            fn: com.gs.return
            args: "Hello"
      - id: 2nd
        fn: com.gs.return
        args: 'parallel task2'
      - id: 3nd
        fn: com.gs.return
        args: 'parallel task3'
  
```
expected output 

```
[
    {
        "success": true,
        "code": 200,
        "message": "",
        "data": [
            {
                "success": true,
                "code": 200,
                "data": "నమస్కారం"
            },
            {
                "success": true,
                "code": 200,
                "data": "parallel task2"
            },
            {
                "success": true,
                "code": 200,
                "data": "Hello"
            }
        ]
    },
    {
        "success": true,
        "code": 200,
        "data": "parallel task2"
    },
    {
        "success": true,
        "code": 200,
        "data": "parallel task3"
    }
]
```
Current Output 
```
[
    {
        "success": true,
        "code": 200,
        "message": "",
        "data": [
            {
                "success": true,
                "code": 200,
                "data": "నమస్కారం"
            },
            {
                "success": true,
                "code": 200,
                "data": "parallel task2"
            },
            {
                "success": true,
                "code": 200,
                "data": "Hello"
            }
        ]
    },
    {
        "success": true,
        "code": 200,
        "data": "parallel task2"
    },
    {
        "success": true,
        "code": 200,
        "data": "parallel task3"
    }
]
```

###########################

Workflow 
```
id: return4
tasks:
  - id: if
    fn: com.gs.if
    condition: <% inputs.query.greet == 'hello' %>
    tasks:
      - id: step1
        fn: com.gs.return
        args: 'Hello!'

  - id: elif1
    fn: com.gs.elif
    condition: <% inputs.query.greet == 'pavan' %>
    tasks:
      - id: step2
        fn: com.gs.return
        args: 'Hello pavan'

  - id: elif2
    fn: com.gs.elif
    condition: <% inputs.query.greet == 'hari' %>
    tasks:
      - id: step3
        fn: com.gs.return
        args: 'Hello Hari'

  - id: else
    fn: com.gs.else
    tasks:
      - id: step4
        fn: com.gs.return
        args: 'Hi developer'
  - id: parallel
    fn: com.gs.parallel
    tasks:
      - id: parallel
        fn: com.gs.parallel
        tasks:
          - id: 1st
            fn: com.gs.return
            args: "నమస్కారం"

          - id: 2nd
            fn: com.gs.return
            args: "नमस्ते"

          - id: 3rd
            fn: com.gs.return
            args: "Hello"
      - id: 2nd
        fn: com.gs.return
        args: 'parallel task2'
      - id: 3nd
        fn: com.gs.return
        args: 'parallel task3'
  
  
  
```
expected output 

```
If greet value is hello

Hello!

 

If greet value is pavan 

Hello pavan

 

If greet value is hari

Hello Hari

 

 

if greet value is null 

`Hi developer`
```
Current Output 
```
If greet value is hello

Hello!

 

If greet value is pavan 

Hello pavan

 

If greet value is hari

Hello Hari


if greet value is null 
`Hi developerssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss`
```

workflow 
```
summary: Returning hello world
tasks:
  - id: return_hello_word
    fn: com.gs.return
    args: 'Hello'

  - id: return_with_status
    fn: com.gs.transform 
    args: <% outputs.return_hello_word.data + inputs.query.word %>
```

expected output
```
Irrespective of the word value 

it should print “Hello“

```
current output 
```
Hello 
```
