### ISSUE TITLE
Allow calling YAML workflow from JS workflow

### ISSUE THREAD

**Issue by rohitgodspeed** [godspeedsystems/gs-node-service#813]
This will allow calling an existing YAML workflow function from an JS/TS function.

for eg., a YAML workflow [functions/validate.yaml]

```
id: validate_workflow
tasks:
  - id: first
    fn: com.gs.transform
    args: <% inputs.body %>
```

and a JS workflow: [functions/login.js]
```
const id = 'myJsWorkflow';
module.exports = (ctx) => {
  const { logger, outputs, functions } = ctx;
  const validate_workflow = functions['validate'](ctx);
  outputs[id] = await validate_workflow({ body: { name: 'Loki' } });
}
```

clild issue of **Allow JS Workflows to be directly called from events**

**Comment by pavan-godspeed** [comment]
This [PR](https://github.com/godspeedsystems/gs-node-service/pull/842) resolves the Issue.

The usage of this method is described below.
## src/functions/native-fn.js:
```js
const id = 'myJsWorkflow';
const {GSStatus} = require('@godspeedsystems/core');

module.exports = async (ctx) => {
  const { outputs, functions } = ctx;
  
  const validate_workflow = functions['validate'];
  
  outputs[id] = await validate_workflow(ctx);

  return new GSStatus(true, 200, undefined, `${ctx.outputs.myJsWorkflow.data}`, undefined);

}
```
## src/functions/validate.yaml:
```yaml
id: validate_workflow
summary:
description:
tasks:
  - id: first
    fn: com.gs.transform
    args: "Called from JS function"
```
## Output:
![Uploading Screenshot from 2023-12-14 19-20-26.png…]()
