### ISSUE TITLE
Axios: Retry mechanism custom status code

### ISSUE THREAD

**Issue by xCodeMuse** [godspeedsystems/gs-node-service#840]
Part of #883 
### The problem
Currently the framework only retry the task execution after the failure & there is no other way to set a custom retry logic. 
for eg. on the statusCode and data

Also, currently it is handled for all tasks whereas it needs to be handled only for API calls over http, grpc, graphql etc. 

### The solution

Linked to [this pull request](https://github.com/godspeedsystems/gs-plugins/pull/125)
- Support retry in gs-plugins/axios. remove from the framework code.
- IF key will be added in the retry snippet of the task to check the condition on gsStatus. 
- inline JS in expected as value for IF statement. This will become the retryCondition() of the axios plugin. 
- this logic will be tested on each retry attempt. if the logic fails no further retry will be made.
- in the retry logic the gsstatus of the failed task will be available in the outputs[taskid]
- This will apply to only axios tasks

```
retry:
    if: <% outputs[taskId].code === 500 && outputs[taskId].data.headers === something %>
    max_attempts: 5
    type: constant
    interval: PT15m
```
### How will we solve
put appropriate changes in core/Interfaces.js to be applied for all the yaml/native fns
