### ISSUE TITLE
Not able to use inputs and output in mappings as placeholders

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#939]
## Version Information
@godspeedsystems/core: 2.3.2

## Current Behavior
We can't use inputs and outputs in mappings as placeholders. Currently, what is happening, inputs and outputs are getting evaluated loadtime, but at that time, inputs and outputs will be blank. So `id` is coming as blank.
For example, sample mapping yaml:
```
get:
  where:
    id: <% inputs?.params?.id %>
  select:
    id: true
    name: true
    email: true
    enabled: true
    roles:
      select:
        name: true
  bName: <% config.bname %>
  cName: <% mappings.sample %>
```

## Expected Behavior
inputs and outputs should go as it is like a placeholder and should get evaluated at the runtime whenever any event is triggered and any workflow is executing.

So what should happen as per the above example, in mappings.sample and config.bname should be evaluated during loadtime because these are the constants but inputs and outputs should go as they are. These should get evaluated during the workflow execution.

**Comment by gurjotkaur20** [comment]
assign

**Comment by gurjotmindgrep** [comment]
https://github.com/godspeedsystems/gs-node-service/blob/2658da5c8c1a729b3b2d872c449656915de218a4/src/godspeed.ts#L14

**Comment by mastersilv3r** [comment]
Shouldn't mappings always be loaded and evaluated at load time? Instead of at run time?

**Comment by gurjotkaur20** [comment]
Let me give an example of my use case: 
In my prisma schema, I have two tables `user` and `user_type` where `user` has a relation with `user_type`.

Request body is fixed e.g.
```
"name": "abc",
"user_type": "admin"
```

If we want to get `user` then in the workflow we need to provide the filters like `where`, `select`, etc.,
But to provide related records information we need to give `where` clause something like this: 
```
where:
  name: <% inputs.body.name %>
  user_type:
     select:
       name: <% inputs.body.user_type %>
```

We have two options here.
- Either we add this `where` filter in the workflow for each entity
- Or we can keep the filter in some `mappings` to keep the workflow unchanges (in case of multiple clients using the same workflow) and `mappings` can be kept separately for different clients. This will keep the main workflow same for all the clients, the variable part would be there in `mappings`.

So, the option 2 is only feasible if `mappings` can take `inputs` and `outputs`.
