### ISSUE TITLE
Axios header based authentication with automatic token refresh using custom authentication function

### ISSUE THREAD

**Issue by kushal-godspeed** [godspeedsystems/gs-node-service#944]
Child of #883 

### The Problem
Current Axios datasource does not allow authentication mechanisms. We need that so that developer can easily setup custom auth, without any boilerplate introduced in his workflow code. This should be doable from the datasource yaml itself.

### The Solution

- [x] Allow a developer to specify the headers used for authentication to the API in the datasource yaml file. Some headers can be hardcoded and determined at service load time. They can be loaded from environment file,for ex. Other headers will be authentication headers which will need to be fetched in runtime, if found null or if authentication has returned failure status from an API call.
- [x] Setting headers in the datasource yaml will add those headers in every call to that datasource.
- [x] can specify custom authentication function in the yaml file. This function will reside in the middlewares folder. This function 
- [x] Default logic to refresh token: by default refresh on A. when header is null or B. when api response gives 401 (or specified custom) status code(s). Developer can give a single or array of status codes which mean authentication failed. 
- [x] Customize the logic to refresh token. Allow to specify a custom function or a workflow which will be run on every response from the API to find out whether API call was successful. If it failed, did it fail because of authentication issues? Here we can specify any custom logic like checking the response status and body. This function will return true if authentication has failed, in which case the authentication method will get triggered.  
  - [x] Either refreshStatusCode or customLogic will be defined. If both are defined customLogic will be used and statusCode will be ignored.
- [x] ensure only one token refresh call is made, concurrent api calls to wait for the response with a timeout which is configurable and has a default value of 5sec and allow overriding the default timeout value from datasource configuration. 
- [x] Sample axios datasource yaml
#### Delhivery OS1

```yaml
# api configuration for salesforce api for saving loan application data
type: axios
base_url: <%`https://${config.tenantId}.sandbox.getos1.com/core/api/v2/`%>
# curlifiedLogs: true #If set will console log curl version of all calls we make to APIs via axios
authn: 
  fn: os1.api.getAuthToken #A JS file in fuinctions folder
  refreshOn: #either statusCode or customLogic will be defined. If both are defined customLogic will be used and statusCode will be ignored.
    statusCode: [401
    ] #array or single code. By default 401 is used if this is not set
    #customLogic: com.biz.isTokenExpired #This function/yaml workflow will run after every API response to check whether it was authenitcated or not. Kept in middlewares folder adjacent to the functions folder
headers:
  Content-Type: application/json
  X-COREOS-REQUEST-ID: ""
```
#### Salesforce
```yaml
# api configuration for salesforce api for saving loan application data
type: api
base_url: <% config.salesforce.loan_url %>
authn: 
  headers: ['Authorization']
  fn: com.lending.salesforceAuthToken #in middlewares folder adjacent to the functions folder
  refreshOn: #either statusCode or customLogic will be defined. If both are defined customLogic will be used and statusCode will be ignored.
    statusCode: [401] #array or single code. By default 401 is used if this is not set
    customLogic: com.biz.isTokenExpired #This function/yaml workflow will run after every API response to check whether it was authenitcated or not. Kept in middlewares folder adjacent to the functions folder

headers:
  Content-Type: application/json
```
### Sample customAuthn Function for Delhivery OS1 datasource yaml above.
```typescript
import { GSContext } from "@godspeedsystems/core";

const axios = require('axios');
const client = axios.create({
    headers: {
        "X-COREOS-TID": process.env.X_COREOS_TID,
        "X-COREOS-REQUEST-ID": "",
        "Content-Type": "application/json"
    }
});

const authUrl = `https://${process.env.X_COREOS_TID}.sandbox.getos1.com/core/api/v1/aaa/auth/client-credentials`;

module.exports = async function (ctx: GSContext) {
    try {
        const res = await client({
            method: 'post',
            url: authUrl,
            data: {
                "clientId": process.env.X_CLIENT_ID,
                "clientSecret": process.env.X_CLIENT_SECRET,
                "audience": "platform:app:coreos"
            }
        })
        const headers =  {
            "X-COREOS-ACCESS": res.data.data.accessToken,
            "X-COREOS-ORIGIN-TOKEN": res.data.data.accessToken,
            "X-COREOS-TID": process.env.X_COREOS_TID,
            "Content-Type": "application/json",
            "X-COREOS-REQUEST-ID": ""
        };
        // ctx.childLogger.error('Auth token successfully refreshed and following headers set: %o', Object.keys(headers));

        return headers;
    } catch (error) {
        ctx?.childLogger.error('Error in refreshing token for OS1 %o', error);
        throw error;
    }
}

// return {
//     "X-COREOS-ORIGIN-TOKEN": process.env.X_COREOS_ACCESS,
//     "X-COREOS-ACCESS": process.env.X_COREOS_ACCESS,
//     "X-COREOS-TID": process.env.X_COREOS_TID
// }
```
### How will we solve
Change the axios plugin
