### ISSUE TITLE
.yml file is not getting read in mappings

### ISSUE THREAD

**Issue by gurjotkaur20** [godspeedsystems/gs-node-service#950]
## Version Information
@godspeedsystems/core: "2.3.2"

## Current Behavior
Not able to refer .yml file in mappings. It should be able to read mappings from .yaml/.yml files.
Filename: `mappings/busi.yml`
If I try to use it in the workflow:
```
  - id: business_one
    fn: datasource.mysql.business.findUnique
    args:
      where:
        id: <% inputs.params.id %>
      select: <% mappings.busi.get.select %>
```

It's giving error:
```
Caught error in evaluation in task id: business_one, error: {"success":false,"message":"Cannot read properties of undefined (reading 'get')","data":"TypeError: Cannot read properties of undefined (reading 'get')\n    at Object.eval [as select] . . . . .. 
```
